// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6yeRCT6IrFYnEM9mPYFoy_hKmpGPMe2A',
    appId: '1:676507613513:web:f7d512b47a686190e24298',
    messagingSenderId: '676507613513',
    projectId: 'chat-tea-9f6e4',
    authDomain: 'chat-tea-9f6e4.firebaseapp.com',
    storageBucket: 'chat-tea-9f6e4.appspot.com',
    measurementId: 'G-EZFXEKH7QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8vF20O3agum1lY6MzHTWQ_RDtNg6zd0',
    appId: '1:676507613513:android:b9410b18b9c3fde7e24298',
    messagingSenderId: '676507613513',
    projectId: 'chat-tea-9f6e4',
    storageBucket: 'chat-tea-9f6e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdMESg4jEvUaVcJZXS8cyOF2XqPR9Wvc4',
    appId: '1:676507613513:ios:9b0380d2ce07bdcfe24298',
    messagingSenderId: '676507613513',
    projectId: 'chat-tea-9f6e4',
    storageBucket: 'chat-tea-9f6e4.appspot.com',
    iosClientId: '676507613513-sfcr2k06ls8lmo7qe72dd62or19b1ebj.apps.googleusercontent.com',
    iosBundleId: 'com.atinity.grouptea',
  );
}
